version: '3.8'

services:
  scheduler:
    build: .
    environment:
      - REPO_URL=https://github.com/youruser/jobs-repo.git
    volumes:
      - ./jobs:/app/jobs
      - ./logs:/app/logs
    restart: unless-stopped
